### ISSUE TITLE
Housekeeping Checklist

### ISSUE THREAD

**Issue by radditude** [revelrylabs/ecto_soft_delete#5]
There's still a few things left to do in order to make this repo an awesome place to contribute. Checklist as follows:

- [x] License
- [x] Readme
     - [x] Links to documentation (https://hexdocs.pm/ecto_soft_delete/api-reference.html_)
     - [x] Links to license
     - [x] Has or links to release instructions
     - [x] Links to Hex page for package
- [x] CI (Travis)
     - [x] Automatic publication on tagged commits is set up (once we figure out how to do that for Hex with Travis)
- [x] Is hooked up to a Slack channel somewhere so we get notifications about issues/PRs
- [x] Issue template (optional but encouraged) - http://wiki.revelry.co/index.php/Open_Source_Issue_Template
